name: Files check CI

on:
  push:
    branches:
      - 'chore/**'
      - 'feat/**'
      - 'fix/**'
      - main
  pull_request:
    branches:
      - 'chore/**'
      - 'feat/**'
      - 'fix/**'
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check License Header
      uses: apache/skywalking-eyes/header@main
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.15.0
